#!/usr/bin/env sh

export BROWSER=/usr/bin/firefox
export EDITOR=/usr/bin/nano
export TERM=/usr/bin/lxterminal

#export SXMO_RTCWAKEINTERVAL=3600
export SXMO_LOCK_SCREEN_OFF=1

xset dpms
xset s 60 60

dotnet /home/mo/coding/ppjackd/bin/Debug/net5.0/ppjackd.dll > ~/ppjackd.log &

feh --bg-fill /home/mo/.bg
/home/mo/.local/bin/audioctl.sh s 50
